*****PP434: Charts 1-4 Clean Up*****

In [1]:
import pandas as pd

***Cleaning Trump 2.0 data***

In [566]:
data2025 = pd.read_csv('data/arrests2025clean.csv')
data2025.columns.to_list()

['apprehension_date',
 'apprehension_state',
 'apprehension_aor',
 'final_program',
 'final_program_group',
 'apprehension_method',
 'apprehension_criminality',
 'case_status',
 'case_category',
 'departed_date',
 'departure_country',
 'final_order_yes_no',
 'final_order_date',
 'birth_year',
 'citizenship_country',
 'gender',
 'apprehension_site_landmark',
 'unique_identifier',
 'apprehension_date_time',
 'duplicate_likely',
 'file_original',
 'sheet_original',
 'row_original']

In [ ]:
columns_to_keep3 = ["apprehension_date", "apprehension_aor", "apprehension_criminality", "unique_identifier", 'birth_year','gender','citizenship_country']
data2025 = data2025[columns_to_keep3]
data2025 = data2025.rename(columns={'apprehension_aor': 'Apprehension AOR', 'unique_identifier': 'Unique Identifier', 'apprehension_date': 'Apprehension Date', 'apprehension_criminality': 'Apprehension Criminality', 'birth_year': 'Birth Year', 'gender': 'Gender', 'citizenship_country': 'Citizenship Country'})

5410

In [ ]:
#Recoding Criminality Column
data2025 = data2025.replace(to_replace="1 Convicted Criminal", value="Convicted")
data2025 = data2025.replace(to_replace="2 Pending Criminal Charges", value="Pending Charges")
data2025 = data2025.replace(to_replace="3 Other Immigration Violator", value="No Criminal Charges")

In [ ]:
#Renaming AOR column to be compatible with the topojson
data2025['Apprehension AOR'] = data2025['Apprehension AOR'].str.replace(' Area of Responsibility', '', regex=False)
data2025 = data2025.rename(columns={'Apprehension AOR': 'aor_nam'})

In [ ]:
data2025['Apprehension MonthYear'] = pd.to_datetime(data2025['Apprehension Date']).dt.strftime('%Y-%m')

#Removing Missing IDs
print("The number of missing IDs in the 2023 to 2025 data is", data2025['Unique Identifier'].isna().sum())
data2025 = data2025.dropna(subset=['Unique Identifier'])

#Checking for Duplicates
data2025[data2025.duplicated(subset=['Unique Identifier', 'Apprehension Date', 'aor_nam'], keep=False)] #6690 duplicates

,Apprehension Date,aor_nam,Apprehension Criminality,Unique Identifier,Birth Year,Gender,Citizenship Country,Apprehension MonthYear
167,2025-10-15,Boston,Convicted,a97cb4422e770e23e17f29858e30b434a067794b,1982.0,Male,DOMINICAN REPUBLIC,2025-10
318,2025-10-15,Baltimore,Convicted,d7dd161d0f282b89d58cf97b841a58a2c7d70759,1987.0,Male,HONDURAS,2025-10
345,2025-10-15,Boston,Convicted,a97cb4422e770e23e17f29858e30b434a067794b,1982.0,Male,DOMINICAN REPUBLIC,2025-10
376,2025-10-15,San Francisco,No Criminal Charges,34d335ca25c36054314810961ec114128dc4b359,1993.0,Male,INDIA,2025-10
377,2025-10-15,San Francisco,No Criminal Charges,34d335ca25c36054314810961ec114128dc4b359,1993.0,Male,INDIA,2025-10
...,...,...,...,...,...,...,...,...
376672,2023-09-01,NaN,No Criminal Charges,d75aa42df32375cd184d043fc7753b169d87dde9,1966.0,Male,ECUADOR,2023-09
376681,2023-09-01,New Orleans,Pending Charges,616ad323e7ffb2ccac244645133269eb6d890d65,1998.0,Male,VENEZUELA,2023-09
376694,2023-09-01,NaN,No Criminal Charges,7deb8017fb1e8262e1425b22d0531512c875bb51,1998.0,Male,SENEGAL,2023-09
376695,2023-09-01,NaN,No Criminal Charges,7deb8017fb1e8262e1425b22d0531512c875bb51,1998.0,Male,SENEGAL,2023-09
376797,2023-09-01,New Orleans,Pending Charges,616ad323e7ffb2ccac244645133269eb6d890d65,1998.0,Male,VENEZUELA,2023-09

In [ ]:
#Removing Duplicates
data2025.drop_duplicates(subset=['Unique Identifier', 'Apprehension Date', 'aor_nam'], inplace=True)

In [ ]:
#Adding Age - birthdate is redacted
data2025['Apprehension Date'] = pd.to_datetime(data2025['Apprehension Date'])
data2025['Age'] = data2025['Apprehension Date'].dt.year - data2025['Birth Year'].dropna().astype(int)

In [ ]:
#Not project related - for the portfolio
kmeansdata = data2025.copy()
kmeansdata.to_csv('data/kmeansdata2025.csv', index=False)

In [ ]:
#Didn't end up using in project, bust still available if you're interested!
arrestsbymonth2025 = data2025.groupby('Apprehension MonthYear').size().reset_index(name='arrests')
arrestsbymonth2025.to_csv('/Users/hannahliu/Desktop/PP434/website/data/arrestsbymonth2025.csv', index=False)

***Cleaning Trump 1.0 Data***

In [ ]:
data2016 = pd.read_csv('data/arrests2016.csv', header=4)
data2017 = pd.read_csv('data/arrests-2017.csv', header=4)
data2018 = pd.read_csv('data/arrests2018.csv', header=4)

/var/folders/1l/yh12s4qx29z26j7mg26bfby80000gn/T/ipykernel_43759/233313211.py:1: DtypeWarning: Columns (4,59,60,102) have mixed types. Specify dtype option on import or set low_memory=False.
  data2017 = pd.read_csv('data/arrests-2017.csv', header=4)
/var/folders/1l/yh12s4qx29z26j7mg26bfby80000gn/T/ipykernel_43759/233313211.py:2: DtypeWarning: Columns (4,58,59,60,102) have mixed types. Specify dtype option on import or set low_memory=False.
  data2018 = pd.read_csv('data/arrests2018.csv', header=4)

In [583]:
columns_to_keep = [
    "Apprehension Date And Time",
    "Apprehension AOR",
    "Numeric Birth Year",
    "Gender",
    "Most Serious Criminal Charge Status",
    "Most Serious Criminal Conviction Charge Code",
    "Citizenship Country",
    "Sequence Number/Unique Identifier"
]

data2017 = data2017[columns_to_keep]
data2016 = data2016[columns_to_keep]
data2018 = data2018[columns_to_keep]

data2017 = pd.concat([data2017, data2016, data2018], ignore_index=True)
full_data_2017 = data2017[columns_to_keep]

In [585]:
data2017['Apprehension Date And Time'] = pd.to_datetime(data2017['Apprehension Date And Time']).dt.strftime('%Y-%m-%d')

/var/folders/1l/yh12s4qx29z26j7mg26bfby80000gn/T/ipykernel_43759/283516911.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data2017['Apprehension Date And Time'] = pd.to_datetime(data2017['Apprehension Date And Time']).dt.strftime('%Y-%m-%d')

In [586]:
#Cleaning for Uniformity
data2017 = data2017.rename(columns={'Apprehension Date And Time': 'Apprehension Date'})
data2017 = data2017.rename(columns={'Numeric Birth Year': 'Birth Year'})
data2017 = data2017.rename(columns={'Sequence Number/Unique Identifier': 'Unique Identifier'})

#AOR
data2017['Apprehension AOR'] = data2017['Apprehension AOR'].str.replace(' Area of Responsibility', '', regex=False)
data2017 = data2017.rename(columns={'Apprehension AOR': 'aor_nam'})

#Criminality
data2017 = data2017.rename(columns={'Most Serious Criminal Charge Status': 'Apprehension Criminality'})
data2017['Apprehension Criminality'] = data2017['Apprehension Criminality'].fillna('No Criminal Charges')
data2017['Apprehension Criminality'] = data2017['Apprehension Criminality'].replace('Turned Over to INS without Prosecution', 'No Criminal Charges')
data2017['Apprehension Criminality'] = data2017['Apprehension Criminality'].replace('Overturned', 'No Criminal Charges')
data2017['Apprehension Criminality'] = data2017['Apprehension Criminality'].replace('Dismissed', 'No Criminal Charges')
data2017['Apprehension Criminality'] = data2017['Apprehension Criminality'].replace('Pending', 'Pending Charges')

In [587]:
data2017

,Apprehension Date,aor_nam,Birth Year,Gender,Apprehension Criminality,Most Serious Criminal Conviction Charge Code,Citizenship Country,Unique Identifier
0,2017-08-16,Phoenix,1964,Male,Convicted,1305,MEXICO,8.631713e+18
1,2017-07-18,Phoenix,1981,Male,Convicted,1312,GUATEMALA,8.579638e+18
2,2016-11-20,Phoenix,1992,Male,Convicted,1315,MEXICO,7.962727e+18
3,2017-08-10,Phoenix,1986,Male,Convicted,3560,MEXICO,6.470752e+18
4,2017-08-17,Phoenix,1978,Male,Convicted,5015,MEXICO,9.734764e+17
...,...,...,...,...,...,...,...,...
399373,2018-02-27,Los Angeles,1978,Male,Convicted,3803,MEXICO,7.496261e+17
399374,2018-08-30,Phoenix,1990,Male,Convicted,5212,MEXICO,3.828758e+18
399375,2018-01-23,Buffalo,1980,Male,Convicted,0301,ECUADOR,9.061895e+18
399376,2018-06-28,Miami,1990,Male,Pending Charges,3704,NICARAGUA,1.854778e+18
399377,2018-01-30,Denver,1992,Male,No Criminal Charges,NaN,CUBA,3.379112e+18

In [588]:
print(data2017['Apprehension Date'].min())
print(data2017['Apprehension Date'].max())

#Dropping the missing IDs
print("The number of missing IDs in the 2023 to 2025 data is", data2017['Unique Identifier'].isna().sum())
data2017 = data2017.dropna(subset=['Unique Identifier'])

2015-10-01
2018-09-30
3166

In [589]:
data2017[data2017.duplicated(subset=['Unique Identifier', 'Apprehension Date', 'aor_nam'], keep=False)] #5739 duplicates

,Apprehension Date,aor_nam,Birth Year,Gender,Apprehension Criminality,Most Serious Criminal Conviction Charge Code,Citizenship Country,Unique Identifier
81,2017-01-23,Miami,1966,Male,Convicted,5012,MEXICO,1.733109e+18
527,2017-02-23,Detroit,1967,Male,Convicted,2399,MEXICO,7.406461e+18
535,2017-06-27,Detroit,1995,Male,Convicted,3599,MEXICO,6.672710e+18
670,2016-11-22,Atlanta,1972,Male,Convicted,5499,MEXICO,3.638435e+18
673,2017-01-12,Atlanta,1988,Male,Pending Charges,5404,HONDURAS,8.225268e+18
...,...,...,...,...,...,...,...,...
397408,2017-10-13,San Francisco,1990,Male,Convicted,35AA,MEXICO,8.822801e+18
397543,2017-10-04,Washington,1996,Male,Pending Charges,5404,HONDURAS,6.046586e+18
397962,2017-10-04,Atlanta,1993,Female,No Criminal Charges,NaN,GUATEMALA,8.658912e+18
398243,2017-10-13,New Orleans,1987,Male,Convicted,5499,MEXICO,2.549999e+16
398870,2017-10-12,Houston,1989,Male,Convicted,5404,MEXICO,8.317631e+18

In [ ]:
#Dropping duplicates
data2017.drop_duplicates(subset=['Unique Identifier', 'Apprehension Date', 'aor_nam'], inplace=True)

In [591]:
#Again, didn't use this in the project, but still available in the folder
data2017['Apprehension MonthYear'] = pd.to_datetime(data2017['Apprehension Date']).dt.strftime('%Y-%m')
arrestsbymonth2017 = data2017.groupby('Apprehension MonthYear').size().reset_index(name='arrests')
arrestsbymonth2017.to_csv('/Users/hannahliu/Desktop/PP434/website/data/arrestsbymonth2017.csv', index=False)

**Chart 1: Comparing Rolling Averages**

In [593]:
daily_arrests2017 = data2017.groupby('Apprehension Date').size().reset_index(name='arrests')
daily_arrests2017['week_rolling_avg'] = daily_arrests2017['arrests'].rolling(window=7).mean()
daily_arrests2017.to_csv('/Users/hannahliu/Desktop/PP434/website/data/dailyarrests2017.csv', index=False)

In [594]:
daily_arrests2025 = data2025.groupby('Apprehension Date').size().reset_index(name='arrests')
daily_arrests2025['week_rolling_avg'] = daily_arrests2025['arrests'].rolling(window=7).mean()
daily_arrests2025

    Apprehension Date  arrests  week_rolling_avg
0          2023-09-01      389               NaN
1          2023-09-02       86               NaN
2          2023-09-03      106               NaN
3          2023-09-04      119               NaN
4          2023-09-05      435               NaN
..                ...      ...               ...
772        2025-10-12      555       1068.714286
773        2025-10-13      701       1020.428571
774        2025-10-14     1350       1023.000000
775        2025-10-15     1454       1021.857143
776        2025-10-16        2        839.142857

[777 rows x 3 columns]

In [596]:
daily_arrests2017['Administration'] = 'Trump 1.0'
daily_arrests2025['Administration'] = 'Trump 2.0'

reference_date1 = pd.to_datetime('2025-01-20')
reference_date2 = pd.to_datetime('2017-01-20')
data2017['date_converted'] = pd.to_datetime(data2017['Apprehension Date'])
data2025['date_converted'] = pd.to_datetime(data2025['Apprehension Date'])
daily_arrests2025['Apprehension Date'] = pd.to_datetime(daily_arrests2025['Apprehension Date'])
daily_arrests2017['Apprehension Date'] = pd.to_datetime(daily_arrests2017['Apprehension Date'])
daily_arrests2025['days_since_jan20'] = ((daily_arrests2025['Apprehension Date'] - reference_date1).dt.days)
daily_arrests2017['days_since_jan20'] = ((daily_arrests2017['Apprehension Date'] - reference_date2).dt.days)

In [597]:
daily_arrests2025.to_csv('data/dailyarrests2025.csv', index=False)
daily_arrests2017.to_csv('data/dailyarrests2017.csv', index=False)
dailyarrestscombined = pd.concat([daily_arrests2017, daily_arrests2025], ignore_index=True)
dailyarrestscombined

,Apprehension Date,arrests,week_rolling_avg,Administration,days_since_jan20
0,2023-09-01,16,NaN,Trump 1.0,2415
1,2023-09-02,5,NaN,Trump 1.0,2416
2,2023-09-03,5,NaN,Trump 1.0,2417
3,2023-09-04,3,NaN,Trump 1.0,2418
4,2023-09-05,8,NaN,Trump 1.0,2419
...,...,...,...,...,...
1515,2025-10-12,555,1068.714286,Trump 2.0,265
1516,2025-10-13,701,1020.428571,Trump 2.0,266
1517,2025-10-14,1350,1023.000000,Trump 2.0,267
1518,2025-10-15,1454,1021.857143,Trump 2.0,268
1519,2025-10-16,2,839.142857,Trump 2.0,269

In [598]:
dailyarrestscombined['Month_Day'] = dailyarrestscombined['Apprehension Date'].dt.strftime('%B %d').str.replace(' 0', ' ')
dailyarrestscombined

,Apprehension Date,arrests,week_rolling_avg,Administration,days_since_jan20,Month_Day
0,2023-09-01,16,NaN,Trump 1.0,2415,September 1
1,2023-09-02,5,NaN,Trump 1.0,2416,September 2
2,2023-09-03,5,NaN,Trump 1.0,2417,September 3
3,2023-09-04,3,NaN,Trump 1.0,2418,September 4
4,2023-09-05,8,NaN,Trump 1.0,2419,September 5
...,...,...,...,...,...,...
1515,2025-10-12,555,1068.714286,Trump 2.0,265,October 12
1516,2025-10-13,701,1020.428571,Trump 2.0,266,October 13
1517,2025-10-14,1350,1023.000000,Trump 2.0,267,October 14
1518,2025-10-15,1454,1021.857143,Trump 2.0,268,October 15
1519,2025-10-16,2,839.142857,Trump 2.0,269,October 16

In [599]:
dailyarrestscombined.to_csv('/Users/hannahliu/Desktop/PP434/website/data/dailyarrestscombined.csv', index=False)

**Chart 2: Arrests by Citizenship Country**

In [603]:
arrests_by_country2017 = data2017[
    (data2017['Apprehension Date'] >= '2017-01-20') & 
    (data2017['Apprehension Date'] <= '2017-10-15')
].groupby('Citizenship Country').agg({
    'Unique Identifier': 'count'
}).reset_index()

arrests_by_country2017.columns = ['Citizenship Country', 'Arrests']

#Adding percentage
arrests_by_country2017['Percentage'] = (
    arrests_by_country2017['Arrests'] / arrests_by_country2017['Arrests'].sum() * 100
).round(2)

arrests_by_country2017 = arrests_by_country2017.sort_values('Arrests', ascending=False)
arrests_by_country2017
arrests_by_country2017["Citizenship Country"] = arrests_by_country2017["Citizenship Country"].str.title()

In [604]:
topcountries2017 = arrests_by_country2017.nlargest(n=15, columns='Arrests')

topcountries2017

Empty DataFrame
Columns: [Citizenship Country, Arrests, Percentage]
Index: []

In [605]:
arrests_by_country2025 = data2025[
    (data2025['Apprehension Date'] >= '2025-01-20') & 
    (data2025['Apprehension Date'] <= '2025-10-15')
].groupby('Citizenship Country').agg({
    'Unique Identifier': 'count'
}).reset_index()

arrests_by_country2025.columns = ['Citizenship Country', 'Arrests']

# Add percentage
arrests_by_country2025['Percentage'] = (
    arrests_by_country2025['Arrests'] / arrests_by_country2025['Arrests'].sum() * 100
).round(2)

arrests_by_country2025 = arrests_by_country2025.sort_values('Arrests', ascending=False)
arrests_by_country2025["Citizenship Country"] = arrests_by_country2025["Citizenship Country"].str.title()
arrests_by_country2025

       Citizenship Country  Arrests  Percentage
108                 Mexico    81286       37.80
70               Guatemala    30791       14.32
75                Honduras    24061       11.19
179              Venezuela    14461        6.72
54             El Salvador    10373        4.82
..                     ...      ...         ...
144    Sint Maarten(Dutch)        1        0.00
34          Cayman Islands        1        0.00
13                 Bahrain        1        0.00
51              East Timor        1        0.00
138  Sao Tome And Principe        1        0.00

[185 rows x 3 columns]

In [606]:
topcountries2025 = arrests_by_country2025.nlargest(n=15, columns='Arrests')
topcountries2025

            Citizenship Country  Arrests  Percentage
108                      Mexico    81286       37.80
70                    Guatemala    30791       14.32
75                     Honduras    24061       11.19
179                   Venezuela    14461        6.72
54                  El Salvador    10373        4.82
120                   Nicaragua     7050        3.28
39                     Colombia     6732        3.13
52                      Ecuador     5833        2.71
43                         Cuba     5516        2.56
50           Dominican Republic     3067        1.43
24                       Brazil     3015        1.40
130                        Peru     2567        1.19
38   China, Peoples Republic Of     2033        0.95
78                        India     1944        0.90
74                        Haiti     1228        0.57

In [607]:
topcountriescombined = pd.concat([topcountries2017, topcountries2025], ignore_index=True)
topcountries2017.to_csv('data/topcountryarrests2017.csv', index=False)
topcountries2025.to_csv('data/topcountryarrests2025.csv', index=False)
topcountriescombined.to_csv('data/topcountryarrests.csv', index=False)

***Combining the Datasets for Charts 3-4***

In [ ]:
#Select columns in the same order for both datasets
data2025_subset = data2025[['Apprehension Date', 'aor_nam', 'Birth Year', 'Age', 'Gender', 'Apprehension Criminality', 'Citizenship Country', 'Unique Identifier']]
data2025_subset['Administration'] = 'Trump 2.0'
data2017_subset = data2017[['Apprehension Date', 'aor_nam', 'Birth Year', 'Age', 'Gender', 'Apprehension Criminality', 'Citizenship Country', 'Unique Identifier']]
data2017_subset['Administration'] = 'Trump 1.0'

combined_data = pd.concat([data2025_subset, data2017_subset], ignore_index=True)

/var/folders/1l/yh12s4qx29z26j7mg26bfby80000gn/T/ipykernel_43759/1255323076.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2025_subset['Administration'] = 'Trump 2.0'
/var/folders/1l/yh12s4qx29z26j7mg26bfby80000gn/T/ipykernel_43759/1255323076.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2017_subset['Administration'] = 'Trump 1.0'

In [ ]:
combined_data['Apprehension Date'] = pd.to_datetime(combined_data['Apprehension Date'])

***Chart 4: Arrests Views***

In [612]:
combined_data['Age Group'] = pd.cut(combined_data['Age'], 
                                     bins=[0, 18, 25, 35, 45, 55, 65, 100], 
                                     labels=['0-17', '18-24', '25-34', '35-44', '45-54', '55-64', '65+'])

In [613]:
full_combined_data = combined_data

In [614]:
# Create long format dataset with gender, age group, and criminality groupings
# Filter data to only include Jan 20 to Oct 15 for each administration

# Filter for Trump 1.0 (2017-01-20 to 2017-10-15), excluding Unknown gender
trump1_filtered = combined_data[
    (combined_data['Administration'] == 'Trump 1.0') &
    (combined_data['Apprehension Date'] >= '2017-01-20') &
    (combined_data['Apprehension Date'] <= '2017-10-15') &
    (combined_data['Gender'] != 'Unknown')
]

# Filter for Trump 2.0 (2025-01-20 to 2025-10-15), excluding Unknown gender
trump2_filtered = combined_data[
    (combined_data['Administration'] == 'Trump 2.0') &
    (combined_data['Apprehension Date'] >= '2025-01-20') &
    (combined_data['Apprehension Date'] <= '2025-10-15') &
    (combined_data['Gender'] != 'Unknown')
]

# Initialize empty dataframe
viewdf = pd.DataFrame(columns=['view', 'characteristic', 'value', 'percentage', 'administration'])

# ===== GENDER GROUPING =====
# Trump 1.0 (2017)
gender_2017 = trump1_filtered.groupby('Gender').size().reset_index(name='value')
gender_2017['view'] = 'gender'
gender_2017['characteristic'] = gender_2017['Gender'].str.lower()
gender_2017['administration'] = 'Trump 1.0'
gender_2017['percentage'] = (gender_2017['value'] / gender_2017['value'].sum())
gender_2017 = gender_2017[['view', 'characteristic', 'value', 'percentage', 'administration']]

# Trump 2.0 (2025)
gender_2025 = trump2_filtered.groupby('Gender').size().reset_index(name='value')
gender_2025['view'] = 'gender'
gender_2025['characteristic'] = gender_2025['Gender'].str.lower()
gender_2025['administration'] = 'Trump 2.0'
gender_2025['percentage'] = (gender_2025['value'] / gender_2025['value'].sum())
gender_2025 = gender_2025[['view', 'characteristic', 'value', 'percentage', 'administration']]

viewdf = pd.concat([viewdf, gender_2017, gender_2025], ignore_index=True)

/var/folders/1l/yh12s4qx29z26j7mg26bfby80000gn/T/ipykernel_43759/3450730259.py:40: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  viewdf = pd.concat([viewdf, gender_2017, gender_2025], ignore_index=True)

In [ ]:
# ===== AGE GROUP GROUPING =====
# Trump 1.0 (2017)
agegroup_2017 = trump1_filtered.groupby('Age Group').size().reset_index(name='value')
agegroup_2017['view'] = 'age group'
agegroup_2017['characteristic'] = agegroup_2017['Age Group'].astype(str)
agegroup_2017['administration'] = 'Trump 1.0'
agegroup_2017['percentage'] = (agegroup_2017['value'] / agegroup_2017['value'].sum())
agegroup_2017 = agegroup_2017[['view', 'characteristic', 'value', 'percentage', 'administration']]

# Trump 2.0 (2025)
agegroup_2025 = trump2_filtered.groupby('Age Group').size().reset_index(name='value')
agegroup_2025['view'] = 'age group'
agegroup_2025['characteristic'] = agegroup_2025['Age Group'].astype(str)
agegroup_2025['administration'] = 'Trump 2.0'
agegroup_2025['percentage'] = (agegroup_2025['value'] / agegroup_2025['value'].sum())
agegroup_2025 = agegroup_2025[['view', 'characteristic', 'value', 'percentage', 'administration']]

viewdf = pd.concat([viewdf, agegroup_2017, agegroup_2025], ignore_index=True)

/var/folders/1l/yh12s4qx29z26j7mg26bfby80000gn/T/ipykernel_43759/1189112037.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  agegroup_2017 = trump1_filtered.groupby('Age Group').size().reset_index(name='value')
/var/folders/1l/yh12s4qx29z26j7mg26bfby80000gn/T/ipykernel_43759/1189112037.py:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  agegroup_2025 = trump2_filtered.groupby('Age Group').size().reset_index(name='value')

In [617]:


# ===== CRIMINALITY GROUPING =====
# Trump 1.0 (2017)
criminality_2017 = trump1_filtered.groupby('Apprehension Criminality').size().reset_index(name='value')
criminality_2017['view'] = 'criminality'
criminality_2017['characteristic'] = criminality_2017['Apprehension Criminality'].astype(str)
criminality_2017['administration'] = 'Trump 1.0'
criminality_2017['percentage'] = (criminality_2017['value'] / criminality_2017['value'].sum())
criminality_2017 = criminality_2017[['view', 'characteristic', 'value', 'percentage', 'administration']]

# Trump 2.0 (2025)
criminality_2025 = trump2_filtered.groupby('Apprehension Criminality').size().reset_index(name='value')
criminality_2025['view'] = 'criminality'
criminality_2025['characteristic'] = criminality_2025['Apprehension Criminality'].astype(str)
criminality_2025['administration'] = 'Trump 2.0'
criminality_2025['percentage'] = (criminality_2025['value'] / criminality_2025['value'].sum())
criminality_2025 = criminality_2025[['view', 'characteristic', 'value', 'percentage', 'administration']]

viewdf = pd.concat([viewdf, criminality_2017, criminality_2025], ignore_index=True)

viewdf

           view       characteristic   value  percentage administration
0        gender               female   22939    0.107055      Trump 2.0
1        gender                 male  191335    0.892945      Trump 2.0
2     age group                 0-17       0         NaN      Trump 1.0
3     age group                18-24       0         NaN      Trump 1.0
4     age group                25-34       0         NaN      Trump 1.0
5     age group                35-44       0         NaN      Trump 1.0
6     age group                45-54       0         NaN      Trump 1.0
7     age group                55-64       0         NaN      Trump 1.0
8     age group                  65+       0         NaN      Trump 1.0
9     age group                 0-17    3949    0.018430      Trump 2.0
10    age group                18-24   38630    0.180285      Trump 2.0
11    age group                25-34   76427    0.356682      Trump 2.0
12    age group                35-44   58041    0.270875      Trump 2.0
13    age group                45-54   28142    0.131338      Trump 2.0
14    age group                55-64    7833    0.036556      Trump 2.0
15    age group                  65+    1250    0.005834      Trump 2.0
16  criminality            Convicted   79277    0.369980      Trump 2.0
17  criminality  No Criminal Charges   70358    0.328355      Trump 2.0
18  criminality      Pending Charges   64639    0.301665      Trump 2.0

In [618]:
viewdf.to_csv('/Users/hannahliu/Desktop/PP434/website/data/arrestviews.csv', index=False)

**Chart 3: Arrests by AOR Map**

In [619]:
data2025

,Apprehension Date,aor_nam,Apprehension Criminality,Unique Identifier,Birth Year,Gender,Citizenship Country,Apprehension MonthYear,Age,date_converted
0,2025-10-16,Washington,No Criminal Charges,e9abff2b0a60f4e081697252a3f1839449c1a7df,2000.0,Male,GUATEMALA,2025-10,25.0,2025-10-16
1,2025-10-16,Atlanta,Convicted,fe94c3cbc82c98ddbc58095356b080115451a003,1999.0,Male,GUATEMALA,2025-10,26.0,2025-10-16
2,2025-10-15,Miami,Pending Charges,232b395785fbbf89219f82087330aefc9ceb3936,1996.0,Male,EL SALVADOR,2025-10,29.0,2025-10-15
3,2025-10-15,Houston,No Criminal Charges,c236342cb81598ea7e45d474caa5e5865deca984,1986.0,Male,EL SALVADOR,2025-10,39.0,2025-10-15
4,2025-10-15,Atlanta,No Criminal Charges,f36c5d824f3df994f0b11480a3fbe8c3902c66d4,1985.0,Male,MEXICO,2025-10,40.0,2025-10-15
...,...,...,...,...,...,...,...,...,...,...
377062,2023-09-01,Los Angeles,Convicted,ce4d0daa245cf16a80255124c294bec3f71008ba,1973.0,Male,MEXICO,2023-09,50.0,2023-09-01
377063,2023-09-01,NaN,No Criminal Charges,ffac23b15079edcda5924d5fd40f3a57cb2e1dbb,1993.0,Male,KYRGYZSTAN,2023-09,30.0,2023-09-01
377064,2023-09-01,NaN,No Criminal Charges,a632cdeac5b00eab74e40dab38afa6e1363311d5,1993.0,Male,KYRGYZSTAN,2023-09,30.0,2023-09-01
377065,2023-09-01,Phoenix,No Criminal Charges,17c8dc3b11362931789f90cca0c466509042dc27,2005.0,Male,GUATEMALA,2023-09,18.0,2023-09-01
377066,2023-09-01,San Antonio,No Criminal Charges,1c460b14af1389f1a09800aa917966f9db95077b,2004.0,Female,CUBA,2023-09,19.0,2023-09-01

In [620]:
aordf = pd.DataFrame(columns=['aor_nam', 'arrests', 'administration'])
aor_2017 = trump1_filtered.groupby('aor_nam').size().reset_index(name='arrests')
aor_2017['administration'] = 'Trump 1.0'
aor_2017 = aor_2017[['aor_nam', 'arrests', 'administration']]

In [621]:
aor_2025 = trump2_filtered.groupby('aor_nam').size().reset_index(name='arrests')
aor_2025['administration'] = 'Trump 2.0'
aor_2025 = aor_2025[['aor_nam', 'arrests', 'administration']]
aor_2025

           aor_nam  arrests administration
0          Atlanta    15059      Trump 2.0
1        Baltimore     3177      Trump 2.0
2           Boston     6815      Trump 2.0
3          Buffalo     2204      Trump 2.0
4          Chicago    12990      Trump 2.0
5           Dallas    16995      Trump 2.0
6           Denver     3967      Trump 2.0
7          Detroit     5060      Trump 2.0
8          El Paso     5851      Trump 2.0
9               HQ       93      Trump 2.0
10       Harlingen     6223      Trump 2.0
11         Houston    16849      Trump 2.0
12     Los Angeles    10301      Trump 2.0
13           Miami    22957      Trump 2.0
14     New Orleans    17201      Trump 2.0
15   New York City     5074      Trump 2.0
16          Newark     5915      Trump 2.0
17    Philadelphia     6178      Trump 2.0
18         Phoenix     6882      Trump 2.0
19  Salt Lake City     6181      Trump 2.0
20     San Antonio    11821      Trump 2.0
21       San Diego     4946      Trump 2.0
22   San Francisco     4495      Trump 2.0
23         Seattle     2850      Trump 2.0
24        St. Paul     4913      Trump 2.0
25      Washington     8664      Trump 2.0

In [622]:
aordf = pd.concat([aordf, aor_2017, aor_2025], ignore_index=True)
aordf['aor_nam'] = aordf['aor_nam'].replace('St. Paul', 'St Paul')
aordf

           aor_nam arrests administration
0          Atlanta   15059      Trump 2.0
1        Baltimore    3177      Trump 2.0
2           Boston    6815      Trump 2.0
3          Buffalo    2204      Trump 2.0
4          Chicago   12990      Trump 2.0
5           Dallas   16995      Trump 2.0
6           Denver    3967      Trump 2.0
7          Detroit    5060      Trump 2.0
8          El Paso    5851      Trump 2.0
9               HQ      93      Trump 2.0
10       Harlingen    6223      Trump 2.0
11         Houston   16849      Trump 2.0
12     Los Angeles   10301      Trump 2.0
13           Miami   22957      Trump 2.0
14     New Orleans   17201      Trump 2.0
15   New York City    5074      Trump 2.0
16          Newark    5915      Trump 2.0
17    Philadelphia    6178      Trump 2.0
18         Phoenix    6882      Trump 2.0
19  Salt Lake City    6181      Trump 2.0
20     San Antonio   11821      Trump 2.0
21       San Diego    4946      Trump 2.0
22   San Francisco    4495      Trump 2.0
23         Seattle    2850      Trump 2.0
24         St Paul    4913      Trump 2.0
25      Washington    8664      Trump 2.0

In [623]:
aordf.to_csv('/Users/hannahliu/Desktop/PP434/website/data/aordf.csv', index=False)

*The Harlingen AOR was added from parts of San Antonio and Houston in FY2022.

**Area Chart of Arrests, filter by AOR**

In [624]:
aorcrimdf = pd.DataFrame(columns=['aor_nam', 'date', 'arrests', 'administration'])

***Checking the Data***

In [632]:
print("The youngest person detained in 2025 was", data2025['Age'].min())
print("The youngest person detained in 2017 was", data2017['Age'].min())
print("The oldest person detained in 2025 was", data2025['Age'].max())
print("The oldest person detained in 2017 was", data2017['Age'].max())

The youngest person detained in 2025 was 0.0
The youngest person detained in 2017 was 7.0
The oldest person detained in 2025 was 92.0
The oldest person detained in 2017 was 105.0

In [630]:
print("The number of rows in 2025 data with Unknown Gender is", (data2025['Gender'] == 'Unknown').sum())
print("The number of rows in 2017 data with Unknown Gender is",(data2017['Gender'] == 'Unknown').sum())
print("The number of rows in 2025 data with missing AOR is", (data2025['aor_nam'].isna().sum()))
print("The number of rows in 2017 data with missing AOR is", (data2017['aor_nam'].isna().sum()))
print("The number of rows in 2017 data with missing Birth Year is", (data2017['Birth Year'].isna().sum()))
print("The number of rows in 2025 data with missing Birth Year is", (data2025['Birth Year'].isna().sum()))

The number of rows in 2025 data with Unknown Gender is 1439
The number of rows in 2017 data with Unknown Gender is 6
The number of rows in 2025 data with missing AOR is 5779
The number of rows in 2017 data with missing AOR is 481
The number of rows in 2017 data with missing Birth Year is 0
The number of rows in 2025 data with missing Birth Year is 1